# the name of the app.  This becomes the root name of all artifacts related to 
# the app.
app_name: {{app_name}}

# Cloud configuration variables
# TODO(axelmagn): convert to deployment config
cloud:
  # GCP Project ID
  project: {{gcp_project}}
  # GCP Region used for all regionalized tasks and artifacts.
  region: {{gcp_region}}
  # GCP Storage path to use as root for all runtime files
  storage_root: {{gcp_storage_root}}


# build configuration steps
build:
  # local directory to use as root of build artifacts
  local_root: "build"

deploy:
  # known issue: deploying scheduled pipelines via cloud build currently 
  # fails, as SDK attempts to re-enable APIs, and cloud build SA does not 
  # have the requisite permissions.
  # TODO(axelmagn): identify necessary role (short term)
  # TODO(axelmagn): implement workaround (long term)
  # starter: 2 * * * *
  pipelines:

pipelines:
