# the name of the app.  This becomes the root name of all artifacts related to 
# the app.
app_name: {{app_name}}

# Secrets can be stored in environment variables, or Cloud Secret Manager.
# Configuration manager will check first for environment variables, 
# then for secrets in secret manager. Secret manager is only checked if the 
# flag `--enable-secret-manager` is passed during invocation.
# 
# TODO(axelmagn): implement secret handling in config.py
# TODO(axelmagn): articulate secret definition format
secrets: {}

# Cloud configuration variables
# TODO(axelmagn): convert to deployment config
cloud:
  name: local
  # GCP Project ID
  project: {{gcp_project}}
  # GCP Region used for all regionalized tasks and artifacts.
  region: {{gcp_region}}
  # GCP Storage path to use as root for all runtime files
  storage_root: {{gcp_storage_root}}


# local paths
local:
  # local directory to use as root of build artifacts
  build_root: "./build"

pipelines:
  hello_world:
    build:
      python_path: {{app_name}}.pipelines.hello_pipeline.hello_pipeline # required
      compile_args:
        # the following args are automatically overwritten: 
        # pipeline_func, package_path, pipeline_name
        pipeline_parameters: # optional
          text: "custom message"
        type_check: True # optional
    run:
      run_args:

  fashion_mnist:
    build:
      python_path: {{app_name}}.pipelines.train_fashion_mnist.pipeline
    run:
      run_args: 

